version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: alex368/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/media
    env_file: .env
    depends_on:
      - db

  frontend:
    image: alex368/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    env_file: .env
    depends_on:
      - backend

  gateway:
    image: alex368/foodgram_gateway
    volumes:
      - static:/staticfiles/
      - media:/media
    env_file: .env
    ports:
      - 9080:80
    depends_on:
      - frontend